### ISSUE TITLE
import requires catalog file?

### ISSUE THREAD

**Issue by caseyjlaw** [chime-frb-open-data/chime-frb-open-data#10]
I was hoping to use some of the data reading and plotting utilities you've made, both for the localizations and the catalog itself. However, I can't import modules from cfod easily due to a requirement for a catalog data file.

I installed by cloning the repo and then `pip install .`. Also tried to do the exact syntax shown in the README, but that did not change the issue with import.

Here's the error upon import:
```
> from cfod import routines
ERROR:Unable to locate CHIME/FRB Catalog.
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-2-5b07eab362e9> in <module>
----> 1 from cfod import routines

~/anaconda3/envs/py37/lib/python3.7/site-packages/cfod/__init__.py in <module>
     26 else:
     27     log.error("Unable to locate CHIME/FRB Catalog.")
---> 28     raise ImportError("Unable to locate CHIME/FRB Catalog.")

ImportError: Unable to locate CHIME/FRB Catalog.
```

**Comment by shinybrar** [comment]
@caseyjlaw Thanks for reporting the issue and I released a new version, `2021.6.3` which should be able to at least let you move forward if not remedy the issue.

## Likely Cause
Most likely, either the machine you are on had no internet connection, or the user did not have sufficient write permissions to fetch the CHIME/FRB Catalogs.

## Background
When `cfod` is run for the first time, it attempts to get the most update-to-date catalog files from `chime-frb.ca`. These files are downloaded to `<some-path>/cfod/data/catalog.[csv|fits]`. The code for this, resides in the `cfod/__init__.py`

```python
BASE_DIR: Path = Path(os.path.dirname(os.path.realpath(__file__)))
DATA_DIR: Path = BASE_DIR / "data"
CSV_CATALOG: Path = DATA_DIR / "catalog.csv"
FITS_CATALOG: Path = DATA_DIR / "catalog.fits"

if os.environ["DEBUG"]:
    log.setLevel(logging.DEBUG)
    log.debug("Logging Level: Debug")

if not len(list(DATA_DIR.glob("catalog.*"))):
    from cfod.utilities import fetch

    log.debug("Fetching CHIME/FRB Catalogs")
    fetch.csv_catalog()
    fetch.fits_catalog()

if CSV_CATALOG.exists():
    catalog = catalogs.Catalogs(filename=CSV_CATALOG.absolute().as_posix())
elif FITS_CATALOG.exists():
    catalog = catalogs.Catalogs(filename=FITS_CATALOG.absolute().as_posix())
else:
    log.error("Unable to locate CHIME/FRB Catalog.")

```

## Changes Implemented
  - The failure to locate the CHIME/FRB Catalog will no longer raise an `ImportError`, but rather just print an error in the console. As a result, now your import should work regardless, but you will be needed to copy the catalog files to the proper location, i.e. `cfod/data/...`
  - I have also implemented a better `DEBUG` mode which you can instantiate by having a env variable, `DEBUG=1` which should implement logs similar to the ones shown below,

  ```bash
shiny@Jupiter:~/workspace/chime-frb/chime-frb-open-data$ DEBUG=1 python3 -c "from cfod import routines"
DEBUG:Logging Level: Debug
DEBUG:Fetching CHIME/FRB Catalogs
DEBUG:Downloading...
DEBUG:URL  : https://storage.googleapis.com/chimefrb-dev.appspot.com/catalog1/chimefrbcat1.csv
DEBUG:File : /home/shiny/workspace/chime-frb/chime-frb-open-data/cfod/data/catalog.csv
DEBUG:Downloading...
DEBUG:URL  : https://storage.googleapis.com/chimefrb-dev.appspot.com/catalog1/chimefrbcat1.fits
DEBUG:File : /home/shiny/workspace/chime-frb/chime-frb-open-data/cfod/data/catalog.fits
DEBUG:Loading Catalog: /home/shiny/workspace/chime-frb/chime-frb-open-data/cfod/data/catalog.csv
  ```

## Action Items
- Download the newest version of `cfod`
- Insure proper read/write permissions for the user, and internet access at least when the python module is imported the first time.
- Run the module in debug mode, to further investigate the issue.


Let me know if you run any other issues, I want to get this resolved as soon as possible.

**Comment by caseyjlaw** [comment]
Ok, thanks for the quick response. If I update and set DEBUG, it works as you show above and I can get the catalog as shown in the docs.
That said, most people probably won't have that set, so maybe better to have it default to DEBUG=0, if the env variable is not set.

**Comment by shinybrar** [comment]
@caseyjlaw Thats a misstep on my part, and i updated the check for debug mode. Its now live on version 2021.6.4

```python
# old-check
if os.environ["DEBUG"]:
    # some code

# new-check
if os.environ.get("DEBUG", false):
    # some code
```

**Comment by caseyjlaw** [comment]
Looks good!
