### ISSUE TITLE
localizer contour plot misspelling

### ISSUE THREAD

**Issue by alfa33333** [chime-frb-open-data/chime-frb-open-data#18]
**Describe the bug**
The contour plot function in the localizer instance is misspelled.

**To Reproduce**
from cfod.routines import localizer
localize = localizer.Localizer(filename='FRB20180725A_localization.h5')
localize.plot()
localize.**coutour_plot()**

**Expected behavior**
It should be contour_plot()

**Environment (please complete the following information):**
 - OS: Ubuntu 20.04
 - Python Environment: python 3.8 ,  cfod v2021.6.4

**Comment by shinybrar** [comment]
@alfa33333 -- you are welcomed to open a pull request to change this. It is a good first issue 👍🏾 

Great catch.
