### ISSUE TITLE
Python 3.6 release?

### ISSUE THREAD

**Issue by caseyjlaw** [chime-frb-open-data/chime-frb-open-data#20]
I am interested in parsing the catalog as a dataframe for a project. It is needed in a complex software environment based on Python 3.6. Is it possible to include that version as a release with the latest catalog?
Currently, `pip install cfod` in python 3.6 returns the 2019 version.

**Comment by shinybrar** [comment]
Hi @caseyjlaw , I looked into making the package backwards compatible with 3.6 -- however we run into couple issues. 
1. Some packages, used at the current version in the project do now support 3.6
2. Type annotations prior to 3.7 could only use names in the current scope, with no forward references of any kind. 
As a result for now, 3.6 will not be supported
